name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (pnpm or npm)
        run: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; else npm ci || npm i; fi

      - name: Type check
        run: npm run type-check || true

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build

      - name: Skip tests (archived)
        run: echo "Tests archived. See docs/reference/tests-archive."

