name: Self-Hosted Smoke (Debian)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # her 30 dakikada bir

jobs:
  smoke:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright (runtime)
        run: |
          npm i -D @playwright/test
          npx playwright install --with-deps

      - name: Web smoke against running service
        env:
          BASE_URL: ${{ secrets.SELFHOST_BASE_URL }}
        run: |
          export BASE_URL=${BASE_URL:-http://localhost}
          echo "Testing BASE_URL=$BASE_URL"
          npx playwright test -c playwright.config.ts

      - name: Health probe (raw)
        env:
          BASE_URL: ${{ secrets.SELFHOST_BASE_URL }}
        run: |
          export BASE_URL=${BASE_URL:-http://localhost}
          curl -sf "$BASE_URL/api/health" | tee selfhosted-health.json


